### ISSUE TITLE
Notepad++ 6.5.2 "fail to import"

### ISSUE THREAD

**Issue by szabolcszijarto** [tlowry/npp-golang#2]
In notepad++ 6.5.2 I get "fail to import" when trying to import this file.
![2014-12-14 17_41_46-_y__ev3_proba go - notepad](https://cloud.githubusercontent.com/assets/5399855/5428162/9a044e14-83b8-11e4-96c5-d8164620b2d9.png)

**Comment by r3wt** [comment]
same issue here

![image](https://cloud.githubusercontent.com/assets/4483325/5700044/5e8e1870-99fb-11e4-9e68-1a384a6615c6.png)

**Comment by tlowry** [comment]
Thanks guys, I've updated the readme in case people run into this issue again.
Closing for now but feel free to comment or open a new issue if this is still a problem after using git clone/download zip.
