### ISSUE TITLE
Following instructions doesn't give me any sort of highlighting

### ISSUE THREAD

**Issue by b4ux1t3** [tlowry/npp-golang#3]
Did an update break this?
![gosyntax](https://cloud.githubusercontent.com/assets/5150833/8386692/5d2c356e-1c20-11e5-9741-9464353bdfc5.PNG)

**Comment by b4ux1t3** [comment]
Scratch that. It only works if the file is saved as .go, but it does work.

**Comment by tlowry** [comment]
You can also change the Language for an unsaved file on the fly like this:
![shot](https://cloud.githubusercontent.com/assets/1682861/8386883/c41a862e-1c4b-11e5-8f8d-4e7e2975babf.png)

**Comment by b4ux1t3** [comment]
Yeah, that's what I did. If you look at the bottom left of my screenshot, you can see it'sset to "Golang" which is what I saved it as. It didn't work until I saved the file. But I think that's a problem with NPP's user defined languages, not your file. :) I'm going to mess with it and submit a bug report to him if it persists.
