### ISSUE TITLE
Implement folders

### ISSUE THREAD

**Issue by Djent-** [tlowry/npp-golang#4]
Notepad++ allows for the collapsing of multi-line comments and other blocks of code. Currently this language file only allows the folding of multi-line comments. 

Feature suggestion: implement the "folding in code" stylers for functions and other bracketed code blocks.

**Comment by hongzhouchen-oceanwing** [comment]
I had created a pull request for folders: [fix {} folding](https://github.com/tlowry/npp-golang/pull/5)

**Comment by Zamiell** [comment]
@hongzhouchen-oceanwing Thanks so much for this!

**Comment by tlowry** [comment]
Sorry for leaving this inactive for so long, I've been really distracted with other things. If this change is working well for you I'll merge the change in.

**Comment by Zamiell** [comment]
Interestingly, this only appears to work if the go file has Windows line endings (\r\n) and the collapsing is completely broken with UNIX line endings (\n). Anyone want to take a look?

**Comment by tlowry** [comment]
Looks like a known issue with Notepad++ User defined languages : http://stackoverflow.com/questions/23098102/udl2-folding-style-2-only-work-with-windows-eol-but-not-unix-eol.

Though it might be better to have folding for windows line endings than none at all.
